
name: Greeting from Fardin
on: push
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: HI there! My name is
        FIRST_NAME: FARDIN
        LAST_NAME: ABDULLAH
      run:
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
